# Generated by Django 4.2.27 on 2026-01-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expected_salary',
        ),
    ]
