# Generated by Django 4.2.27 on 2026-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_profile_current_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='current_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
