# Generated by Django 4.2.27 on 2026-01-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_current_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='applied_at',
        ),
    ]
