# Generated by Django 4.2.27 on 2026-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_profile_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
